esphome:
  name: athom-relay-x2
  friendly_name: Athom Relay X2

esp8266:
  board: esp01_1m
  restore_from_flash: True
  early_pin_init: False

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

#Add after install on device
wifi:
  use_address: 192.168.212.223

# Somente se for ESP8266 sem bateria
sensor:
  - platform: adc
    pin: VCC
    name: Tensão de Entrada
    update_interval: 60s
    id: tensao_entrada
    internal: False
    disabled_by_default: False

switch:
  - platform: gpio
    pin:
      number: GPIO5
      inverted: False
    name: Relay 1
    id: relay_1
    internal: False
    disabled_by_default: False
    # RESTORE_DEFAULT_OFF or RESTORE_DEFAULT_ON or RESTORE_INVERTED_DEFAULT_OFF or RESTORE_INVERTED_DEFAULT_ON or ALWAYS_OFF or ALWAYS_ON or DISABLED
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: &interlock_group_1 [relay_1, relay_2]
    interlock_wait_time: 0ms
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay_1

  - platform: gpio
    pin:
      number: GPIO4
      inverted: False
    name: Relay 2
    id: relay_2
    internal: False
    disabled_by_default: False
    # RESTORE_DEFAULT_OFF or RESTORE_DEFAULT_ON or RESTORE_INVERTED_DEFAULT_OFF or RESTORE_INVERTED_DEFAULT_ON or ALWAYS_OFF or ALWAYS_ON or DISABLED
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: *interlock_group_1
    interlock_wait_time: 0ms
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay_2

  - platform: template
    name: Todos
    id: todos
    internal: False
    disabled_by_default: False
    optimistic: False
    # RESTORE_DEFAULT_OFF or RESTORE_DEFAULT_ON or RESTORE_INVERTED_DEFAULT_OFF or RESTORE_INVERTED_DEFAULT_ON or ALWAYS_OFF or ALWAYS_ON or DISABLED
    restore_mode: DISABLED
    lambda: |-
      if (id(relay_1).state || id(relay_2).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action: 
      then:
        - switch.turn_on: relay_1
        - switch.turn_on: relay_2
    turn_off_action:
      then:
        - switch.turn_off: relay_1
        - switch.turn_off: relay_2

status_led:
  pin: 
    number: GPIO2
    inverted: False