esphome:
  name: athom-relay-x2
  friendly_name: Athom Relay X2

esp8266:
  board: esp01_1m
  restore_from_flash: True
  early_pin_init: False

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

switch:
  - platform: gpio
    pin:
      number: GPIO5
      inverted: False
    name: Relay 1
    id: relay_1
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay_1

status_led:
  pin: 
    number: GPIO2
    inverted: False