esphome:
  name: athom-garage-door
  friendly_name: Athom Garage Door

esp8266:
  board: esp01_1m
  restore_from_flash: True
  early_pin_init: False

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    id: contact
    name: contact
    device_class: garage_door
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on_off:
          milliseconds: 10
          seconds: 0
          minutes: 0
          hours: 0

  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    name: Button 1
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on_off:
          milliseconds: 10
          seconds: 0
          minutes: 0
          hours: 0
    on_press: 
      then:
        switch.toggle: relay_1

switch:
  - platform: gpio
    pin:
      number: GPIO5
      inverted: False
    name: Relay 1
    id: relay_1
    internal: False
    disabled_by_default: False
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - delay:
        milliseconds: 0
        seconds: 1
        minutes: 0
        hours: 0
    - switch.turn_off: relay_1

cover:
  - platform: template
    device_class: garage
    name: "Garage Door"
    lambda: "return id(contact).state ? COVER_OPEN : COVER_CLOSED;"
    open_action:
      then:
       - if:
          condition:
            lambda: 'return !id(contact).state;'
          then:
              - switch.turn_on: relay_1
    stop_action:
      - switch.turn_on: relay_1
    close_action:
      then:
       - if:
          condition:
            lambda: 'return id(contact).state;'
          then:
            - switch.turn_on: relay_1

status_led:
  pin: 
    number: GPIO12
    inverted: False
