#############################ESP32-WROOM-32D###########################
  # bl0906_tx_pin: GPIO12
  # bl0906_rx_pin: GPIO14
  # button_pin:    GPIO0
  # led_pin:       GPIO15
#############################ESP32-WROOM-32D###########################

esphome:
  name: athom-em-2
  friendly_name: Athom Energy Meter 2

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  variant: ESP32C3
  framework:
    type: arduino
    version: recommended

# esp32:
#   board: esp32dev
#   flash_size: 4MB
#   variant: ESP32
#   framework:
#     type: arduino
#     version: recommended

esp32_ble_tracker:
  scan_parameters:
    active: True

bluetooth_proxy:
  active: True

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

#Add after install on device
wifi:
  use_address: 192.168.212.223

external_components:
  - source: github://athom-tech/esp32-configs@main
    components: bl0906
    refresh: 0s

globals:
  - id: id_Energy_sum_persist
    type: float
    restore_value: yes
    initial_value: '0.0'
  - id: id_Energy_sum_lastvalue
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: id_Energy_1_persist
    type: float
    restore_value: yes
    initial_value: '0.0'
  - id: id_Energy_1_lastvalue
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: id_Energy_2_persist
    type: float
    restore_value: yes
    initial_value: '0.0'
  - id: id_Energy_2_lastvalue
    type: float
    restore_value: no
    initial_value: '0.0'

uart:
  tx_pin: GPIO7
  rx_pin: GPIO8
  baud_rate: 19200
  id: uart_bl0906

light:
  - platform: status_led
    name: Status LED
    id: blue_led
    disabled_by_default: False
    internal: False
    pin: GPIO10

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: Button
    id: button_1
    disabled_by_default: False
    internal: False

sensor:
  - platform: bl0906
    id: id_bl0906
    update_interval: 5s
    frequency:
      name: 'Frequency'
      id: 'Frequency'
      internal: False
      disabled_by_default: False
    temperature:
      name: 'Temperature'
      id: 'Temperature'
      internal: False
      disabled_by_default: False
    voltage:
      name: 'Voltage'
      id: 'Voltage'
      internal: False
      disabled_by_default: False
    channel_1:
      current:
        name: 'Current_1'
        id: 'Current_1'
        internal: False
        disabled_by_default: False
      power:
        name: 'Power_1'
        id: 'Power_1'
        internal: False
        disabled_by_default: False
      energy:
        id: 'Energy_1'
        name: 'Energy_1_Internal'
        internal: True
        disabled_by_default: False
    channel_2:
      current:
        name: 'Current_2'
        id: 'Current_2'
        internal: False
        disabled_by_default: False
      power:
        name: 'Power_2'
        id: 'Power_2'
        internal: False
        disabled_by_default: False
      energy:
        id: 'Energy_2'
        name: 'Energy_2_Internal'
        internal: True
        disabled_by_default: False
    total_energy:
      name: 'Total_Energy'
      id: 'Energy_sum'
      internal: True
      disabled_by_default: False
    total_power:
      name: 'Total_Power'
      id: 'Total_Power'
      internal: False
      disabled_by_default: False

  - platform: copy
    name: 'Total_Energy'
    id: Energy_sum_persist
    internal: False
    disabled_by_default: False
    source_id: Energy_sum
    filters:
      - lambda: |-
          if(id(id_Energy_sum_lastvalue) == 0.0  )
          {
            id(id_Energy_sum_lastvalue) = id(Energy_sum).state;
          }
          if(x < id(id_Energy_sum_persist))
          {
            float delta =  x - id(id_Energy_sum_lastvalue);
            id(id_Energy_sum_persist) += delta;
            id(id_Energy_sum_lastvalue) = x;
          }
          else
          {
            id(id_Energy_sum_persist) = x;
          }
          return id(id_Energy_sum_persist);

  - platform: copy
    name: 'Energy_1'
    id: Energy_1_persist
    source_id: Energy_1
    internal: False
    disabled_by_default: False
    filters:
      - lambda: |-
          if(id(id_Energy_1_lastvalue) == 0.0  )
          {
            id(id_Energy_1_lastvalue) = id(Energy_1).state;
          }
          if(x < id(id_Energy_1_persist))
          {
            float delta =  x - id(id_Energy_1_lastvalue);
            id(id_Energy_1_persist) += delta;
            id(id_Energy_1_lastvalue) = x;
          }
          else
          {
            id(id_Energy_1_persist) = x;
          }
          return id(id_Energy_1_persist);

  - platform: copy
    name: 'Energy_2'
    id: Energy_2_persist
    source_id: Energy_2
    internal: False
    disabled_by_default: False
    filters:
      - lambda: |-
          if(id(id_Energy_2_lastvalue) == 0.0  )
          {
            id(id_Energy_2_lastvalue) = id(Energy_2).state;
          }
          if(x < id(id_Energy_2_persist))
          {
            float delta =  x - id(id_Energy_2_lastvalue);
            id(id_Energy_2_persist) += delta;
            id(id_Energy_2_lastvalue) = x;
          }
          else
          {
            id(id_Energy_2_persist) = x;
          }
          return id(id_Energy_2_persist);

button:
  - platform: template
    name: Reset Energy
    id: reset_energy
    entity_category: config
    internal: False
    disabled_by_default: False
    on_press:
      then:
        - globals.set:
            id: id_Energy_1_persist
            value: '0.0'
        - globals.set:
            id: id_Energy_2_persist
            value: '0.0'
        - globals.set:
            id: id_Energy_sum_persist
            value: '0.0'
        - bl0906.reset_energy: id_bl0906