esphome:
  name: athom-relay-x8
  friendly_name: Athom Relay X8

esp8266:
  board: esp01_1m
  restore_from_flash: True
  early_pin_init: False

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

#Add after install on device
wifi:
  use_address: 192.168.212.223

switch:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: False
    name: Relay 1
    id: relay_1
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: &interlock_group_1 [relay_1, relay_2, relay_3, relay_4]
    interlock_wait_time: 0ms
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay_1

  - platform: gpio
    pin:
      number: GPIO14
      inverted: False
    name: Relay 2
    id: relay_2
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: *interlock_group_1
    interlock_wait_time: 0ms
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay_2

  - platform: gpio
    pin:
      number: GPIO12
      inverted: False
    name: Relay 3
    id: relay_3
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: *interlock_group_1
    interlock_wait_time: 0ms
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay_3

  - platform: gpio
    pin:
      number: GPIO13
      inverted: False
    name: Relay 4
    id: relay_4
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: *interlock_group_1
    interlock_wait_time: 0ms
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay_4

  - platform: gpio
    pin:
      number: GPIO15
      inverted: False
    name: Relay 5
    id: relay_5
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: &interlock_group_2 [relay_5, relay_6, relay_7, relay_8]
    interlock_wait_time: 0ms
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay_5

  - platform: gpio
    pin:
      number: GPIO0
      inverted: False
    name: Relay 6
    id: relay_6
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: *interlock_group_2
    interlock_wait_time: 0ms
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay_6

  - platform: gpio
    pin:
      number: GPIO4
      inverted: False
    name: Relay 7
    id: relay_7
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: *interlock_group_2
    interlock_wait_time: 0ms
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay_7

  - platform: gpio
    pin:
      number: GPIO5
      inverted: False
    name: Relay 8
    id: relay_8
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: *interlock_group_2
    interlock_wait_time: 0ms
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay_8

  - platform: template
    name: Todos
    id: todos
    internal: False
    disabled_by_default: False
    optimistic: False
    restore_mode: DISABLED
    lambda: |-
      if (id(relay_1).state || id(relay_2).state || id(relay_3).state || id(relay_4).state || id(relay_5).state || id(relay_6).state || id(relay_7).state || id(relay_8).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action: 
      then:
        - switch.turn_on: relay_1
        - switch.turn_on: relay_2
        - switch.turn_on: relay_3
        - switch.turn_on: relay_4
        - switch.turn_on: relay_5
        - switch.turn_on: relay_6
        - switch.turn_on: relay_7
        - switch.turn_on: relay_8
    turn_off_action:
      then:
        - switch.turn_off: relay_1
        - switch.turn_off: relay_2
        - switch.turn_off: relay_3
        - switch.turn_off: relay_4
        - switch.turn_off: relay_5
        - switch.turn_off: relay_6
        - switch.turn_off: relay_7
        - switch.turn_off: relay_8

status_led:
  pin: 
    number: GPIO2
    inverted: False