esphome:
  name: irrigaca-com-sonoff-4ch
  friendly_name: Irrigação com Sonoff 4CH

esp8266:
  board: esp01_1m
  restore_from_flash: True
  early_pin_init: False

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    name: Button 1
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on_off: 10ms
    on_press: 
      then:
        switch.toggle: relay_1

  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    id: button_2
    name: Button 2
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on_off: 10ms
    on_press: 
      then:
        switch.toggle: relay_2

  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    id: button_3
    name: Button 3
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on_off: 10ms
    on_press: 
      then:
        switch.toggle: relay_3

  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    id: button_4
    name: Button 4
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on_off: 10ms
    on_press: 
      then:
        switch.toggle: relay_4

switch:
  - platform: gpio
    pin:
      number: GPIO12
      inverted: False
    name: Relay 1
    id: relay_1
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
#    interlock: &interlock_group_1 [relay_1, relay_2]
#    interlock_wait_time: 0ms
#    on_turn_on:
#    - delay: 500ms
#    - switch.turn_off: relay_1

  - platform: gpio
    pin:
      number: GPIO5
      inverted: False
    name: Relay 2
    id: relay_2
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
#    interlock: *interlock_group_1
#    interlock_wait_time: 0ms
#    on_turn_on:
#    - delay: 500ms
#    - switch.turn_off: relay_2

  - platform: gpio
    pin:
      number: GPIO4
      inverted: False
    name: Relay 3
    id: relay_3
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
#    interlock: &interlock_group_2 [relay_3, relay_4]
#    interlock_wait_time: 0ms
#    on_turn_on:
#    - delay: 500ms
#    - switch.turn_off: relay_3

  - platform: gpio
    pin:
      number: GPIO15
      inverted: False
    name: Relay 4
    id: relay_4
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
#    interlock: *interlock_group_2
#    interlock_wait_time: 0ms
#    on_turn_on:
#    - delay: 500ms
#    - switch.turn_off: relay_4

  - platform: template
    name: Todos
    id: todos
    internal: False
    disabled_by_default: False
    optimistic: False
    restore_mode: DISABLED
    lambda: |-
      if (id(relay_1).state || id(relay_2).state || id(relay_3).state || id(relay_4).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action: 
      then:
        - switch.turn_on: relay_1
        - switch.turn_on: relay_2
        - switch.turn_on: relay_3
        - switch.turn_on: relay_4
    turn_off_action:
      then:
        - switch.turn_off: relay_1
        - switch.turn_off: relay_2
        - switch.turn_off: relay_3
        - switch.turn_off: relay_4

status_led:
  pin: 
    number: GPIO13
    inverted: False

sensor:
  - platform: adc
    pin: A0
    name: Sensor de umidade
    id: sensor_de_umidade
    disabled_by_default: False
    internal: False
    update_interval: 5s
    unit_of_measurement: "%"
    filters:
      - median:
          window_size: 21
          send_every: 4
          send_first_at: 1
      - calibrate_linear:
          - 0.01367 -> 100.00
          - 0.01660 -> 0.00    
      - lambda: |
          if (x < 0) return 0; 
          else if (x > 100) return 100;
          else return (x);    
    accuracy_decimals: 4

  - platform: adc
    pin: 34
    name: Humidade do Solo da Amoreira #1
    id: humidade_do_solo_1
    disabled_by_default: False
    internal: False
    update_interval: 5s
    unit_of_measurement: "%"
    attenuation: auto
    filters:
      - median:
          window_size: 7
          send_every: 4
          send_first_at: 1
      - calibrate_linear:
          - 1.1 -> 100
          - 2.5 -> 0
      - lambda: | 
          if (x < 1) return 0; 
          else return (x);
    accuracy_decimals: 0

  - platform: adc
    pin: 35
    name: Humidade do Solo da Lichia #2
    id: humidade_do_solo_2
    disabled_by_default: False
    internal: False
    update_interval: 5s
    unit_of_measurement: "%"
    attenuation: auto
    filters:
      - median:
          window_size: 7
          send_every: 4
          send_first_at: 1
      - calibrate_linear:
          - 1.1 -> 100
          - 2.5 -> 0
      - lambda: |
          if (x < 1) return 0; 
          else return (x);
    accuracy_decimals: 0

  - platform: adc
    pin: 32
    name: Humidade do Solo do Limoeiro #3
    id: humidade_do_solo_3
    disabled_by_default: False
    internal: False
    update_interval: 5s
    unit_of_measurement: "%"
    attenuation: auto
    filters:
      - median:
          window_size: 7
          send_every: 4
          send_first_at: 1
      - calibrate_linear:
          - 1.1 -> 100
          - 2.5 -> 0
      - lambda: |
          if (x < 1) return 0; 
          else return (x);
    accuracy_decimals: 0


switch:
  - platform: gpio
    pin: 33
    name: Solenoide da Bomba
    id: solenoide_bomba
    # internal: True
    inverted: True
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 25
    name: Solenoide do Limoeiro
    id: solenoide_limoeiro
    # internal: True
    inverted: True
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 26
    name: Solenoide da Lichia
    id: solenoide_lichia
    # internal: True
    inverted: True
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 27
    name: Solenoide da Amoreira
    id: solenoide_amoreira
    # internal: True
    inverted: True
    restore_mode: ALWAYS_OFF