binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
    name: "Button"
    on_multi_click:
    - timing:
      - OFF for 5s to 8s
      - ON for at least 0.5s
      then:
        - logger.log : "01_5 to 8 : All off"
        - switch.turn_off: relay_1
        - switch.turn_off: relay_2
        - switch.turn_off: relay_3
        - switch.turn_off: usb
        - output.turn_on: red_led
        - output.turn_on: blue_led
    - timing:
      - OFF for 2s to 4s
      - ON for at least 0.5s
      then:
        - logger.log : "02_2 to 4 : All on"
        - switch.turn_on: relay_1
        - switch.turn_on: relay_2
        - switch.turn_on: relay_3
        - switch.turn_on: usb
        - output.turn_off: red_led
        - output.turn_off: blue_led
    - timing:
      - OFF for at most 1s
      - ON for at most 0.5s
      - OFF for at most 1s
      - ON for at most 0.5s
      - OFF for at most 1s
      - ON for at most 0.5s
      - OFF for at most 1s
      - ON for at most 0.5s
      - OFF for at most 1s
      - ON for at least 0.5s
      then:
        - logger.log : "03_5 times : All Toggle"
        - switch.toggle: relay_1
        - switch.toggle: relay_2
        - switch.toggle: relay_3
        - switch.toggle: usb
        - output.turn_off: red_led
        - output.turn_on: blue_led
    - timing:
      - OFF for at most 1s
      - ON for at most 0.5s
      - OFF for at most 1s
      - ON for at most 0.5s
      - OFF for at most 1s
      - ON for at most 0.5s
      - OFF for at most 1s
      - ON for at least 0.5s
      then:
        - logger.log : "04_4 times : USB toggle"
        - switch.toggle: usb
        - output.turn_on: red_led
        - output.turn_off: blue_led
    - timing:
      - OFF for at most 1s
      - ON for at most 0.5s
      - OFF for at most 1s
      - ON for at most 0.5s
      - OFF for at most 1s
      - ON for at least 0.5s
      then:
        - logger.log : "05_3 times : R3 toggle"
        - switch.toggle: relay_3
        - output.turn_on: red_led
        - output.turn_on: blue_led
    - timing:
      - OFF for at most 1s
      - ON for at most 0.5s
      - OFF for at most 1s
      - ON for at least 0.5s
      then:
        - logger.log : "06_2 times : R2 toggle"
        - switch.toggle: relay_2
        - output.turn_on: red_led
        - output.turn_off: blue_led
    - timing:
      - OFF for at most 1s
      - ON for at least 0.5s
      then:
        - logger.log : "07_1 time : R1 toggle"
        - switch.toggle: relay_1
        - output.turn_off: red_led
        - output.turn_on: blue_led

  # Physical Button A
  - platform: gpio
    name: "Button A"
    id: button_a
    pin:
      number: GPIO04
      mode: INPUT_PULLUP
      inverted: true

    filters:
      - delayed_on: 10ms

    on_press:
      - if:
          condition:
            switch.is_off: relay_a_decoupled
          then:
            - switch.toggle: relay_a

    on_multi_click:
      # single click detection
      - timing:
        - ON for at most 900ms
        - OFF for at least 600ms
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: "A"
                gesture: "single_click"

      # double click detection
      - timing:
          - ON for at most 500ms
          - OFF for at most 400ms
          - ON for at most 500ms
          - OFF for at least 250ms
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: "A"
                gesture: "double_click"

      # hold detection
      - timing:
          - ON for at least 1s
        then:
          - while:
              condition:
                binary_sensor.is_on: button_a
              then:
                - light.toggle: led_status
                - homeassistant.event:
                    event: esphome.on_gesture
                    data:
                      button: "A"
                      gesture: "button_hold"
                - delay: 100ms
          - light.turn_off: led_status

  - platform: gpio
    name: "Button B"
    id: button_b
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: true

    filters:
      - delayed_on: 10ms

    on_press:
      - if:
          condition:
            switch.is_off: relay_b_decoupled
          then:
            - switch.toggle: relay_b

    on_multi_click:
      # single click detection
      - timing:
        - ON for at most 900ms
        - OFF for at least 600ms
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: "B"
                gesture: "single_click"

      # double click detection
      - timing:
          - ON for at most 500ms
          - OFF for at most 400ms
          - ON for at most 500ms
          - OFF for at least 250ms
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: "B"
                gesture: "double_click"

      # hold detection
      - timing:
          - ON for at least 1s
        then:
          - while:
              condition:
                binary_sensor.is_on: button_b
              then:
                - light.toggle: led_status
                - homeassistant.event:
                    event: esphome.on_gesture
                    data:
                      button: "B"
                      gesture: "button_hold"
                - delay: 100ms
          - light.turn_off: led_status

  - platform: gpio
    name: "Button C"
    id: button_c
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
      inverted: true

    filters:
      - delayed_on: 10ms

    on_press:
      - if:
          condition:
            switch.is_off: relay_c_decoupled
          then:
            - switch.toggle: relay_c

    on_multi_click:
      # single click detection
      - timing:
        - ON for at most 900ms
        - OFF for at least 600ms
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: "C"
                gesture: "single_click"

      # double click detection
      - timing:
          - ON for at most 500ms
          - OFF for at most 400ms
          - ON for at most 500ms
          - OFF for at least 250ms
        then:
          - homeassistant.event:
              event: esphome.on_gesture
              data:
                button: "C"
                gesture: "double_click"

      # hold detection
      - timing:
          - ON for at least 1s
        then:
          - while:
              condition:
                binary_sensor.is_on: button_c
              then:
                - light.toggle: led_status
                - homeassistant.event:
                    event: esphome.on_gesture
                    data:
                      button: "C"
                      gesture: "button_hold"
                - delay: 100ms
          - light.turn_off: led_status
