esphome:
  name: pzem004t
  friendly_name: PZEM004T

esp8266:
  board: esp8285
  restore_from_flash: True
  early_pin_init: False

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

uart:
  - id: uart1
    tx_pin: D2
    rx_pin: D1
    baud_rate: 9600
    stop_bits: 1

  - id: uart2
    tx_pin: D4
    rx_pin: D3
    baud_rate: 9600
    stop_bits: 1

modbus:
  - id: modbus1
    uart_id: uart1

  - id: modbus2
    uart_id: uart2

sensor:
  - platform: pzemac
    modbus_id: modbus1
    current:
      name: PZEM Fase 1 Corrente
      id: pzem_fase_1_corrente
      disabled_by_default: False
      internal: False
    voltage:
      name: PZEM Fase 1 Tensão
      id: pzem_fase_1_tensao
      disabled_by_default: False
      internal: False
    energy:
      name: PZEM Fase 1 Energia
      id: pzem_fase_1_energia
      unit_of_measurement: kWh
      internal: False
      disabled_by_default: False
      accuracy_decimals: 3
      filters:
          - multiply: 0.001
    power:
      name: PZEM Fase 1 Potência
      id: pzem_fase_1_potencia
      disabled_by_default: False
      internal: False
    frequency:
      name: PZEM Fase 1 frequência
      id: pzem_fase_1_frequencia
      internal: False
      disabled_by_default: False
    power_factor:
      name: PZEM Fase 1 Fator de Potência
      id: pzem_fase_1_fator_de_potencia
      internal: False
      disabled_by_default: False
    update_interval: 2s    
    address: 1

  - platform: pzemac
    modbus_id: modbus2
    current:
      name: PZEM Fase 1 Corrente
      id: pzem_fase_1_corrente
      disabled_by_default: False
      internal: False
    voltage:
      name: PZEM Fase 1 Tensão
      id: pzem_fase_1_tensao
      disabled_by_default: False
      internal: False
    energy:
      name: PZEM Fase 1 Energia
      id: pzem_fase_1_energia
      unit_of_measurement: kWh
      internal: False
      disabled_by_default: False
      accuracy_decimals: 3
      filters:
          - multiply: 0.001
    power:
      name: PZEM Fase 1 Potência
      id: pzem_fase_1_potencia
      disabled_by_default: False
      internal: False
    frequency:
      name: PZEM Fase 1 frequência
      id: pzem_fase_1_frequencia
      internal: False
      disabled_by_default: False
    power_factor:
      name: PZEM Fase 1 Fator de Potência
      id: pzem_fase_1_fator_de_potencia
      internal: False
      disabled_by_default: False 
    address: 1

  - platform: template
    name: Total de Energia
    icon: mdi:lightning-bolt
    id: total_de_energia
    internal: False
    disabled_by_default: False
    lambda: |-
      return (id(pzem_fase_1_energia).state + id(pzem_fase_2_energia).state);
    unit_of_measurement: kWh
    update_interval: 1s
    
  - platform: template
    name: Total de Corrente
    icon: mdi:current-ac
    id: total_de_corrente
    internal: False
    disabled_by_default: False
    lambda: |-
      return (id(pzem_fase_1_corrente).state + id(pzem_fase_2_corrente).state);
    unit_of_measurement: A
    update_interval: 1s
    
  - platform: template
    name: Total de Potência
    icon: mdi:flash
    id: total_de_potencia
    internal: False
    disabled_by_default: False
    lambda: |-
      return (id(pzem_fase_1_potencia).state + id(pzem_fase_2_potencia).state);
    unit_of_measurement: W
    update_interval: 1s
    
  - platform: template
    name: Média de Tensão
    id: media_de_tensao
    internal: False
    disabled_by_default: False
    icon: mdi:sine-wave
    lambda: |-
      return (id(pzem_fase_1_tensao).state + id(pzem_fase_2_tensao).state)/2;
    unit_of_measurement: V
    update_interval: 1s

  - platform: total_daily_energy
    name: "Pzem total energia diária"
    power_id: pzem_total_energia_diaria
    internal: False
    disabled_by_default: False
    filters:
      - multiply: 0.001
    accuracy_decimals: 3
    unit_of_measurement: kWh

  - platform: adc
    pin: VCC
    name: Tensão do ESP
    id: tensao_do_esp
    internal: False
    disabled_by_default: False
