number:
  - platform: template
    name: Calibração de Temperatura
    id: temp_calibration
    min_value: -5.0
    max_value: 5.0
    step: 0.1
    restore_value: True
    optimistic: True
    disabled_by_default: False
    internal: False
    
  - platform: template
    name: Calibração de Umidade
    id: humidity_calibration
    min_value: -10.0
    max_value: 10.0
    step: 0.1
    restore_value: True
    optimistic: True
    disabled_by_default: False
    internal: False

sensor:
  - platform: dht
    pin: GPIO15
    temperature:
      name: Temperatura
      internal: False
      disabled_by_default: False
      filters:
        - lambda: |-
            return x + id(temp_calibration).state;
    humidity:
      name: Umidade
      internal: False
      disabled_by_default: False
      filters:
        - lambda: |-
            return x + id(humidity_calibration).state;
    update_interval: 60s

number:
  - platform: template
    name: Calibração de Temperatura (%)
    id: temp_calibration
    min_value: -5.0
    max_value: 5.0
    step: 0.1
    restore_value: True
    optimistic: True
    disabled_by_default: False
    internal: False
    
  - platform: template
    name: Calibração de Umidade (%)
    id: humidity_calibration
    min_value: -10.0
    max_value: 10.0
    step: 0.1
    restore_value: True
    optimistic: True
    disabled_by_default: False
    internal: False

sensor:
  - platform: dht
    pin: GPIO15
    temperature:
      name: Temperatura
      internal: False
      disabled_by_default: False
      filters:
        - lambda: |-
            return x * (1.0 + id(temp_calibration).state / 100.0)
    humidity:
      name: Umidade
      internal: False
      disabled_by_default: False
      filters:
        - lambda: |-
            return x * (1.0 + id(humidity_calibration).state / 100.0);
    update_interval: 60s