number:
  - platform: template
    name: Limite Umidade Abaixo
    id: liga_relay
    min_value: 0.0
    max_value: 100.0
    step: 1.0
    restore_value: True
    optimistic: True
    disabled_by_default: False
    internal: False
    on_value: 
      then:
        - component.update: soil_hum

  - platform: template
    name: Limite Umidade Acima
    id: desliga_relay
    min_value: 0.0
    max_value: 100.0
    step: 1.0
    restore_value: True
    optimistic: True
    disabled_by_default: False
    internal: False
    on_value: 
      then:
        - component.update: soil_hum

sensor:
  - platform: dht
    pin: GPIO15
    temperature:
      name: Temperatura
      internal: False
      disabled_by_default: False
    humidity:
      name: Umidade
      id: soil_hum
      internal: False
      disabled_by_default: False
    update_interval: 60s
    on_value:
      then:
        - lambda: |-
            float umidade = id(soil_hum).state;
            float liga_valor = id(liga_relay).state;
            float desliga_valor = id(desliga_relay).state;

            // Lógica para o relay 1
            if (umidade < liga_valor) {
              id(relay_1).turn_on();
            } else if (umidade >= desliga_valor) {
              id(relay_1).turn_off();
            }