esphome:
  name: monitoramento-agua
  friendly_name: Monitoramento de Água

esp8266:
  board: esp01_1m
  restore_from_flash: True
  early_pin_init: False

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

# Add after install on device
wifi:
  use_address: 192.168.212.223

switch:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: False
    name: Sentido da Válvula
    id: sentido_da_valvula
    internal: False
    disabled_by_default: False
    # RESTORE_DEFAULT_OFF or RESTORE_DEFAULT_ON or RESTORE_INVERTED_DEFAULT_OFF or RESTORE_INVERTED_DEFAULT_ON or ALWAYS_OFF or ALWAYS_ON or DISABLED
    restore_mode: RESTORE_DEFAULT_OFF
#    interlock: &interlock_group_1 [sentido_da_valvula, relay_2]
#    interlock_wait_time: 0ms
#    on_turn_on:
#    - delay: 500ms
#    - switch.turn_off: sentido_da_valvula

  - platform: gpio
    pin:
      number: GPIO14
      inverted: False
    name: Energia da Válvula
    id: energia_da_valvula
    internal: False
    disabled_by_default: False
    # RESTORE_DEFAULT_OFF or RESTORE_DEFAULT_ON or RESTORE_INVERTED_DEFAULT_OFF or RESTORE_INVERTED_DEFAULT_ON or ALWAYS_OFF or ALWAYS_ON or DISABLED
    restore_mode: RESTORE_DEFAULT_OFF
#    interlock: *interlock_group_1
#    interlock_wait_time: 0ms
#    on_turn_on:
#    - delay: 500ms
#    - switch.turn_off: energia_da_valvula

sensor:
  - platform: pulse_counter
    pin: D5
    unit_of_measurement: "L/min"
    accuracy_decimals: 2
    update_interval: 60s
    internal: False
    disabled_by_default: False
    id: water_meter_house
    name: Water Meter House
    filters:
    - lambda: return (x / 450.0);

    total:
      unit_of_measurement: "L"
      name: Water Meter Total
      internal: False
      disabled_by_default: False
      update_interval: 60s
      id: water_meter_total
      accuracy_decimals: 2
      filters:
      - lambda: return (x / 450.0);