esphome:
  name: sonoff-dual-r3-lite
  friendly_name: Sonoff Dual R3 Lite

esp32:
  board: esp32dev
  framework:
    type: arduino

esp32_ble_tracker:
  scan_parameters:
    active: True

bluetooth_proxy:
  active: True

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: True
    id: switch_1
    name: Switch 1
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press: 
      then:
        switch.toggle: relay_1
    on_release: 
      then:
        - switch.toggle: relay_1

# Se for pulsador remover o on_release

  - platform: gpio
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: True
    id: switch_2
    name: Switch 2
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press: 
      then:
        - switch.toggle: relay_2
    on_release: 
      then:
        - switch.toggle: relay_2
        
# Se for pulsador remover o on_release

switch:
  - platform: gpio
    pin:
      number: GPIO14
      inverted: False
    name: Relay 1
    id: relay_1
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: &interlock_group_1 [relay_1, relay_2]
    interlock_wait_time: 0ms
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay_1

  - platform: gpio
    pin:
      number: GPIO27
      inverted: False
    name: Relay 2
    id: relay_2
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: *interlock_group_1
    interlock_wait_time: 0ms
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay_2

  - platform: template
    name: Todos
    id: todos
    internal: False
    disabled_by_default: False
    optimistic: False
    restore_mode: DISABLED
    lambda: |-
      if (id(relay_1).state || id(relay_2).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action: 
      then:
        - switch.turn_on: relay_1
        - switch.turn_on: relay_2
    turn_off_action:
      then:
        - switch.turn_off: relay_1
        - switch.turn_off: relay_2

status_led:
  pin: 
    number: GPIO13
    inverted: False
