esphome:
  name: sonoff-pow-r316d
  friendly_name: Sonoff Pow R316D

esp32:
  board: nodemcu-32s

esp32_ble_tracker:
  scan_parameters:
    active: True

bluetooth_proxy:
  active: True

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

uart:
  rx_pin: GPIO16
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    name: Button 1
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on_off:
          milliseconds: 10
          seconds: 0
          minutes: 0
          hours: 0
    on_click:
      - max_length:
          milliseconds: 350
          seconds: 0
          minutes: 0
          hours: 0
        then:
          switch.toggle: relay_1
      - min_length:
          milliseconds: 360
          seconds: 0
          minutes: 0
          hours: 0
        max_length:
          milliseconds: 0
          seconds: 3
          minutes: 0
          hours: 0
        then:
          - if:
              condition:
                binary_sensor.is_on: page
              then:
                binary_sensor.template.publish:
                  id: page
                  state: OFF
              else:
                binary_sensor.template.publish:
                  id: page
                  state: ON

  - platform: template # this is a fake sensor to tell the screen which info to show on display
    id: page
    publish_initial_state: True
    internal: True

  - platform: template
    name: Subordinate Device
    id: subordinate_device_on
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    lambda: |-
      if (isnan(id(power).state)) {
        return {};
      } else if (id(power).state > 4) {
        // Running
        return true;
      } else {
        // Not running
        return false;
      }
display:
  platform: tm1621
  id: tm1621_display
  cs_pin: GPIO25
  data_pin: GPIO14
  read_pin: GPIO26
  write_pin: GPIO27
  lambda: |-
    if (id(page).state) {
      it.display_voltage(true);
      it.display_kwh(false);
      it.printf(0, "%.1f", id(voltage).state);
      it.printf(1, "%.1f", id(current).state);
    } else {  
      it.display_voltage(false);
      it.display_kwh(true);
      it.printf(0, "%.1f", id(energy).state);
      it.printf(1, "%.1f", id(current).state);
    }
output:
  - platform: ledc
    id: led
    pin:
      number: GPIO18
      inverted: True

sensor:
  - platform: cse7766
    voltage:
      name: voltage
      id: voltage
      filters:
        - throttle_average:
            milliseconds: 0
            seconds: 5
            minutes: 0
            hours: 0
      internal: False
      disabled_by_default: False
    current:
      name: Current
      id: current
      filters:
        - throttle_average:
            milliseconds: 0
            seconds: 5
            minutes: 0
            hours: 0
      internal: False
      disabled_by_default: False
    power:
      name: Power
      id: power
      filters:
        - throttle_average:
            milliseconds: 0
            seconds: 5
            minutes: 0
            hours: 0
      internal: False
      disabled_by_default: False
    energy:
      name: Energy
      id: energy
      filters:
        - throttle_average:
            milliseconds: 0
            seconds: 5
            minutes: 0
            hours: 0
      internal: False
      disabled_by_default: False
    apparent_power:
      name: Apparent Power
      id: apparent_power
      filters:
        - throttle_average:
            milliseconds: 0
            seconds: 5
            minutes: 0
            hours: 0
      internal: False
      disabled_by_default: False

switch:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: False
    name: Relay 1
    id: relay_1
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - delay: 
          milliseconds: 500
          seconds: 0
          minutes: 0
          hours: 0
      - light.turn_on: switch_led
    on_turn_off:
      - delay: 
          milliseconds: 500
          seconds: 0
          minutes: 0
          hours: 0
      - light.turn_off: switch_led

light:
  - platform: monochromatic
    id: switch_led
    output: led
    internal: True

status_led:
  pin: 
    number: GPIO15
    inverted: True