substitutions:
  device_name: nspanel01
  friendly_name: nspanel01
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
preferences:
  flash_write_interval: 1min

logger:

api:

ota:
  - platform: esphome

mdns:
  disabled: False

captive_portal:

web_server:
  port: 80
  local: True
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

#Add after install on device
wifi:
  use_address: 192.168.212.117

time:
  - platform: homeassistant
    id: homeassistant_time
    update_interval: 60s

  - platform: sntp
    id: sntp_time
    timezone: America/Sao_Paulo
#    timezone: "GMT+3"
    update_interval: 60s
    servers:
     - a.st1.ntp.br
     - b.st1.ntp.br
     - c.st1.ntp.br

button:
  - platform: factory_reset
    name: Reset
    id: Reset
    entity_category: config
    internal: False
    disabled_by_default: False

  - platform: safe_mode
    name: Safe Mode
    entity_category: config
    internal: False
    disabled_by_default: False
  
  - platform: restart
    name: Restart
    entity_category: config
    internal: False
    disabled_by_default: False

binary_sensor:
  - platform: status
    name: Status
    internal: False
    disabled_by_default: False
    publish_initial_state: True

text_sensor:
  - platform: wifi_info
    ip_address: 
      name: IP Address
      entity_category: diagnostic
      internal: False
      disabled_by_default: False
      update_interval: 60s
    ssid: 
      name: SSID
      entity_category: diagnostic
      internal: False
      disabled_by_default: False
      update_interval: 60s
  - platform: version
    name: Esphome version
    internal: False
    disabled_by_default: False
    hide_timestamp: True

sensor:
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    internal: False
    disabled_by_default: False
    update_interval: 60s
    entity_category: diagnostic
  
  - platform: wifi_signal
    name: WiFi Signal dBm
    id: wifi_signal_dbm
    internal: False
    disabled_by_default: False
    update_interval: 60s
    entity_category: diagnostic
    device_class: signal_strength

  - platform: copy
    name: WiFi Signal Percent
    id: wifi_signal_percent
    source_id: wifi_signal_dbm
    internal: False
    disabled_by_default: False
    unit_of_measurement: "%"
    entity_category: diagnostic
    filters: 
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      - esphome/nspanel_esphome_advanced.yaml
      - esphome/nspanel_esphome_addon_ble_tracker.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml