substitutions:
  name: sonoff-tx-ultimate
  friendly_name: Sonoff TX Ultimate
  relay_count: "4"

packages:
  smarthomeyourself.tx-ultimate: github://bernardesarthur/sonoff-tx-ultimate-for-esphome/tx_ultimate_us.yaml@main
  myesphome: github://bernardesarthur/myesphome/base.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false

esp32_ble_tracker:
  scan_parameters:
    active: True

bluetooth_proxy:
  active: True