esphome:
  name: sonoff-basic
  friendly_name: Sonoff Basic

esp8266:
  board: esp01_1m
  restore_from_flash: True
  early_pin_init: False

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    name: Button 1
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on_off:
          milliseconds: 10
          seconds: 0
          minutes: 0
          hours: 0
    on_press: 
      then:
      -  switch.toggle: relay_1

switch:
  - platform: gpio
    pin:
      number: GPIO12
      inverted: False
    name: Relay 1
    id: relay_1
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
#    on_turn_on:
#    - delay:
#        milliseconds: 500
#        seconds: 0
#        minutes: 0
#        hours: 0
#    - switch.turn_off: relay_1

status_led:
  pin: 
    number: GPIO13
    inverted: False