esphome:
  name: sonoff-m5-2c
  friendly_name: Sonoff M5 2C

esp32:
  board: esp32dev
  framework:
    type: arduino

esp32_ble_tracker:
  scan_parameters:
    active: True

bluetooth_proxy:
  active: True

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    name: Button 1
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on_off: 10ms
    on_press: 
      then:
        switch.toggle: relay_1

  - platform: gpio
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
      inverted: True
    id: button_2
    name: Button 2
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on_off: 10ms
    on_press: 
      then:
        switch.toggle: relay_2

switch:
  - platform: gpio
    pin:
      number: GPIO23
      inverted: False
    name: Relay 1
    id: relay_1
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
#    on_turn_on:
#    - delay: 500ms
#    - switch.turn_off: relay_1

  - platform: gpio
    pin:
      number: GPIO19
      inverted: False
    name: Relay 2
    id: relay_2
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - output.turn_on: led_2
#    - delay: 500ms
#    - switch.turn_off: relay_2

  - platform: template
    name: Todos
    id: todos
    internal: False
    disabled_by_default: False
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on: 
      then:
        - switch.turn_on: relay_1
        - switch.turn_on: relay_2
    on_turn_off: 
      then:
        - switch.turn_off: relay_1
        - switch.turn_off: relay_2

output:
  - platform: gpio
    id: led_2
    pin:
      number: GPIO22
      inverted: False

  - platform: ledc
    id: pwm_output
    pin:
      number: GPIO18
      inverted: False
    frequency: 1000 Hz

light:
  - platform: status_led
    name: LED
    id: led_status
    pin:
      number: GPIO05
      inverted: True
    internal: True
    disabled_by_default: False
    restore_mode: ALWAYS_OFF

  - platform: monochromatic
    output: pwm_output
    name: LEDs
    id: leds
    internal: False
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
