esphome:
  name: relay_and_binary_sensor
  friendly_name: Template Relay and Binary Sensor

esp8266:
  board: esp01_1m
  restore_from_flash: True
  early_pin_init: False

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

#Add after install on device
wifi:
  use_address: 192.168.212.223
  # Desabilita a re-conexão contínua à rede para economizar energia (somente se for a bateria)
  fast_connect: True
  # NONE or LIGHT or HIGH
  power_save_mode: HIGH

# Deep Sleep para economizar bateria (somente se for a bateria)
deep_sleep:
  run_duration: 5s  # Tempo que o ESP8266 ficará ligado
  sleep_duration: 60s  # Tempo de sono antes de ligar novamente

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    name: Button 1
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press: 
      then:
        - switch.toggle: buttonpress
    on_multi_click: 
      - timing: 
          - ON for at least 2s
        then:
          - binary_sensor.template.publish:
              id: long_press
              state: ON

  - platform: template
    name: Long Press
    id: long_press
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    on_press:
      - delay: 500ms
      - binary_sensor.template.publish:
          id: long_press
          state: OFF

  - platform: gpio
    pin: 
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    id: switch_1
    name: Switch 1
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press: 
      then:
        - switch.toggle: buttonpress
    on_release: 
      then:
        - switch.toggle: buttonpress

# Se for pulsador remover o on_release

# Somente se for a bateria e se for ESP8266
sensor:
  - platform: adc
    pin: VCC
    name: Tensão da Bateria
    update_interval: 60s
    id: tensao_bateria
    internal: False
    disabled_by_default: False

- platform: template
  name: Nível da Bateria
  id: nivel_bateria
  lambda: |-
    // Considera que a tensão da bateria vai de 3.0V (0%) até 4.2V (100%)
    float tensao = id(tensao_bateria).state * 3.3;
    float percentual = (tensao - 3.0) * 100.0 / (4.2 - 3.0);
    if (percentual > 100) {
      return 100;
    } else if (percentual < 0) {
      return 0;
    } else {
      return percentual;
    }
  unit_of_measurement: "%"
  update_interval: 60s
  internal: False
  disabled_by_default: False

# Somente se for ESP8266 sem bateria
#sensor:
#  - platform: adc
#    pin: VCC
#    name: Tensão da Bateria
#    update_interval: 60s
#    id: tensao_entrada
#    internal: False
#    disabled_by_default: False

switch:
  - platform: gpio
    pin:
      number: GPIO12
      inverted: False
    name: Button Press
    id: buttonpress
    internal: True
    disabled_by_default: False
    # RESTORE_DEFAULT_OFF or RESTORE_DEFAULT_ON or RESTORE_INVERTED_DEFAULT_OFF or RESTORE_INVERTED_DEFAULT_ON or ALWAYS_OFF or ALWAYS_ON or DISABLED
    restore_mode: ALWAYS_OFF

  - platform: template
    name: Click
    id: click
    internal: False
    disabled_by_default: False
    # RESTORE_DEFAULT_OFF or RESTORE_DEFAULT_ON or RESTORE_INVERTED_DEFAULT_OFF or RESTORE_INVERTED_DEFAULT_ON or ALWAYS_OFF or ALWAYS_ON or DISABLED
    restore_mode: DISABLED
    optimistic: False
    lambda: |-
      if (id(buttonpress).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: buttonpress
      - delay: 1s
      - switch.turn_off: buttonpress
    turn_off_action:
      - switch.turn_off: buttonpress

  - platform: template
    name: Hold
    id: hold
    internal: False
    disabled_by_default: False
    # RESTORE_DEFAULT_OFF or RESTORE_DEFAULT_ON or RESTORE_INVERTED_DEFAULT_OFF or RESTORE_INVERTED_DEFAULT_ON or ALWAYS_OFF or ALWAYS_ON or DISABLED
    restore_mode: DISABLED
    optimistic: False
    lambda: |-
      if (id(buttonpress).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: buttonpress
      - delay: 5s
      - switch.turn_off: buttonpress
    turn_off_action:
      - switch.turn_off: buttonpress

status_led:
  pin: 
    number: GPIO13
    inverted: False