esphome:
  name: time_based_cover
  friendly_name: Time Based Cover

esp32:
  board: esp32dev
  framework:
    type: arduino

esp32_ble_tracker:
  scan_parameters:
    active: True

bluetooth_proxy:
  active: True

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: True
    id: switch_1
    name: Switch 1
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on_off:
          milliseconds: 10
          seconds: 0
          minutes: 0
          hours: 0

  - platform: gpio
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: True
    id: switch_2
    name: Switch 2
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on_off:
          milliseconds: 10
          seconds: 0
          minutes: 0
          hours: 0

  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    id: contact
    name: contact
    device_class: garage_door
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on_off:
          milliseconds: 10
          seconds: 0
          minutes: 0
          hours: 0
      
switch:
  - platform: gpio
    pin:
      number: GPIO14
      inverted: False
    name: Relay 1
    id: relay_1
    internal: False
    disabled_by_default: False
    restore_mode: ALWAYS_OFF
    interlock: &interlock_group_1 [relay_1, relay_2]
    on_turn_on:
    - delay:
        milliseconds: 0
        seconds: 0
        minutes: 2
        hours: 0
    - switch.turn_off: relay_1

  - platform: gpio
    pin:
      number: GPIO27
      inverted: False
    name: Relay 2
    id: relay_2
    internal: False
    disabled_by_default: False
    restore_mode: ALWAYS_OFF
    interlock: *interlock_group_1
    on_turn_on:
    - delay:
        milliseconds: 0
        seconds: 0
        minutes: 2
        hours: 0
    - switch.turn_off: relay_2

status_led:
  pin: 
    number: GPIO13
    inverted: False

cover:
  - platform: time_based
    name: Time Based Cover
    id: time_based_cover
    internal: False
    disabled_by_default: False
    assumed_state: True
    open_action:
      then:
       - if:
          condition:
            lambda: 'return !id(contact).state;'
          then:
              - switch.turn_on: relay_1
    open_duration:
      milliseconds: 0
      seconds: 0
      minutes: 2
      hours: 0
    close_action:
      then:
       - if:
          condition:
            lambda: 'return id(contact).state;'
          then:
            - switch.turn_on: relay_2
    close_duration:
      milliseconds: 0
      seconds: 0
      minutes: 2
      hours: 0
    stop_action:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2
