esphome:
  name: time_based_cover
  friendly_name: Time Based Cover

esp32:
  board: esp32dev
  framework:
    type: arduino

esp32_ble_tracker:
  scan_parameters:
    active: True

bluetooth_proxy:
  active: True

packages:
  remote_package:
    url: https://github.com/bernardesarthur/myesphome
    ref: main
    refresh: 300s
    files:
      - base.yaml

#Add after install on device
wifi:
  use_address: 192.168.212.223

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: True
    id: switch_1
    name: Switch 1
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on: 10ms
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: True
    id: switch_2
    name: Switch 2
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on: 10ms
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    id: contact
    name: contact
    device_class: garage_door
    internal: False
    disabled_by_default: False
    publish_initial_state: True
    filters: 
      - delayed_on: 10ms
      - delayed_off: 10ms
      
switch:
  - platform: gpio
    pin:
      number: GPIO14
      inverted: False
    name: Relay 1
    id: relay_1
    internal: False
    disabled_by_default: False
    # RESTORE_DEFAULT_OFF or RESTORE_DEFAULT_ON or RESTORE_INVERTED_DEFAULT_OFF or RESTORE_INVERTED_DEFAULT_ON or ALWAYS_OFF or ALWAYS_ON or DISABLED
    restore_mode: ALWAYS_OFF
    interlock: &interlock_group_1 [relay_1, relay_2]
    interlock_wait_time: 0ms
    on_turn_on:
    - delay: 2min
    - switch.turn_off: relay_1

  - platform: gpio
    pin:
      number: GPIO27
      inverted: False
    name: Relay 2
    id: relay_2
    internal: False
    disabled_by_default: False
    # RESTORE_DEFAULT_OFF or RESTORE_DEFAULT_ON or RESTORE_INVERTED_DEFAULT_OFF or RESTORE_INVERTED_DEFAULT_ON or ALWAYS_OFF or ALWAYS_ON or DISABLED
    restore_mode: ALWAYS_OFF
    interlock: *interlock_group_1
    interlock_wait_time: 0ms
    on_turn_on:
    - delay: 2min
    - switch.turn_off: relay_2

status_led:
  pin: 
    number: GPIO13
    inverted: False

cover:
  - platform: time_based
    name: Time Based Cover
    id: time_based_cover
    internal: False
    disabled_by_default: False
    assumed_state: True
    open_action:
      then:
       - if:
          condition:
            lambda: 'return !id(contact).state;'
          then:
              - switch.turn_on: relay_1
    open_duration: 2min
    close_action:
      then:
       - if:
          condition:
            lambda: 'return id(contact).state;'
          then:
            - switch.turn_on: relay_2
    close_duration: 2min
    stop_action:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2
